123 body index refactor modularization
ai-cfia/nachet-frontend pull request #124
Opened 2024-04-09 18:14 UTC by ChromaticPanic

Ref #123 

Fixes #122

2024-04-09 20:39 UTC, rngadam requested changes
would like to see some unit tests here given the complexity of the change

2024-04-12 13:03 UTC, MaxenceGui commented on src/common/tests/loadcapturetocache.test.tsx
> +// describe("decodeTiff", () => {
Might be a dumb question, but can you mock the dependencies?

2024-04-12 13:37 UTC, MaxenceGui approved these changes
I like the reorganization of the code. I feel like I can undeestand more easily what is happening and where I can find what I need. As for the issue with the tiff image. It seems to be fix as I didn't have any issue doing a classification

![image](https://github.com/ai-cfia/nachet-frontend/assets/96267006/39ede495-d550-40f6-b604-4ac894c0cf34)

Image appear the first time, and the bouding box are around the seeds

2024-04-16 14:14 UTC, CFIALeronB approved these changes

2024-04-16 14:49 UTC, merged