Implement English-French Translation
ai-cfia/nachet-frontend pull request #187
Opened 2024-08-20 20:22 UTC by ClemZ31

This pull request implements English-French translation in the application. It includes changes to several files to add support for internationalization using the i18next library. The `i18n` module is imported and initialized with the necessary configuration for supporting English and French languages. The translation keys are used in the code to display localized text. The changes also include updating the text in various components to use the translation keys instead of hard-coded strings.

Fixes #47

2024-08-20 22:15 UTC, ChromaticPanic approved these changes, later dismissed
Need to run the prettier formatter to satisfy linter . Otherwise LGTM!

2024-08-21 16:01 UTC, Francois-Werbrouck submitted a review, later dismissed
I see some workflow not passing. Other than that LGTM! 
Can you take some time Thursday to give us  (me) a topo on how the translation actually works? I'm quite curious :)

2024-08-22 18:58 UTC, ClemZ31 commented
# How does it work ?

In this [file](https://github.com/ai-cfia/nachet-frontend/blob/655fa08b5c652273d5525c0a47be7b14b8e69285/src/components/header/appbar/index.tsx), there is the select tag used to change language.  It works with the file i18n.js and the import i18next, which allows the website to change dynamically the language of the texts. 

1. Imports and Initialization:
 i18next and react-i18next are imported and initialized in [i18n.js](https://github.com/ai-cfia/nachet-frontend/blob/655fa08b5c652273d5525c0a47be7b14b8e69285/src/i18n.js).

2. Translation JSON Files: These files are imported and added to the resources. They contain the actual translations for each language : [French](https://github.com/ai-cfia/nachet-frontend/blob/655fa08b5c652273d5525c0a47be7b14b8e69285/public/locales/fr/translation.json) and [English](https://github.com/ai-cfia/nachet-frontend/blob/655fa08b5c652273d5525c0a47be7b14b8e69285/public/locales/en/translation.json).

3. Using Translations in Components:

- The `useTranslation` hook is used to access the `t` function, which retrieves the translated text based on the current language. Example : `{t('seed_classification_interface')}`
- In the [header file](https://github.com/ai-cfia/nachet-frontend/blob/655fa08b5c652273d5525c0a47be7b14b8e69285/src/components/header/appbar/index.tsx, the `Select` component allows users to switch languages. When a language is selected, `i18next.changeLanguage` is called to update the language, and every components are updated accordingly.

2024-08-22 19:17 UTC, RussellJimmies requested changes

2024-08-22 19:17 UTC, RussellJimmies commented on public/locales/fr/translation.json
> +    "email_address": "Adresse email",
```suggestion
    "email_address": "Adresse de courriel",
```

2024-08-22 19:17 UTC, RussellJimmies commented on public/locales/fr/translation.json
> +    "bounding_box": "Cadre d'objet",
```suggestion
    "bounding_box": "Rectangle englobant",
```
https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/8400239/rectangle-englobant

2024-08-22 19:17 UTC, RussellJimmies commented on public/locales/fr/translation.json
> +    "creative_commons_terms_and_conditions_header": "Termes et Conditions",
```suggestion
    "creative_commons_terms_and_conditions_header": "Conditions d'utilisation",
```
https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/26527155/conditions-generales-dutilisation

2024-08-27 13:59 UTC, RussellJimmies approved these changes

2025-09-26 14:54 UTC, closed without merging